//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MainDemo.rc
//
#define IDR_MAINFRAME                   128
#define MainForm                        129
#define MainFormMainMenu                130
#define FrameGrabber                    131
#define Overlays_imgBitmapOverlay       132
#define Overlays                        133
#define MotionDetection                 134
#define VideoProcessing                 135
#define Reencoding                      136
#define TVTuner                         137
#define VideoSource                     138
#define Audio                           139
#define Recording                       140
#define NetworkStreaming                141
#define Player                          142
#define Display_imgLogo                 143
#define Display                         144
#define SnapForm                        145
#define tbrPlayer                       1000
#define mmoLog                          1001
#define edtDVDateTime                   1002
#define edtFrameCount                   1003
#define edtStoragePath                  1004
#define btnFormAudio                    1005
#define btnFormRecording                1006
#define btnFormNetworkStreaming         1007
#define btnFormPlayer                   1008
#define btnFormFrameGrabber             1009
#define btnFormMotionDetection          1010
#define btnFormOverlays                 1011
#define btnFormVideoProcessing          1012
#define btnFormDisplay                  1013
#define btnFormReencoding               1014
#define btnFormTVTuner                  1015
#define btnFormVideoSource              1016
#define dlgOpen                         1017
#define mmoFrameCaptureLog              1018
#define btnResetCaptureZoomSize         1019
#define edtCaptureZoomSize              1020
#define tbrCaptureZoomSize              1021
#define edtAVIAutoFilePrefix            1022
#define rdgAutoFileName1                1023
#define rdgAutoFileName2                1024
#define rdgAutoFileName                 1025
#define btnBurstModeStop                1026
#define btnBurstModeJPEGFile            1027
#define btnBurstModeBMPFile             1028
#define btnBurstModeTBitmap             1029
#define edtBurstCount                   1030
#define edtBurstInterval                1031
#define grbBurstMode                    1032
#define chkUseThisFileName              1033
#define edtUseThisFileName              1034
#define btnOneShotTBitmap               1035
#define btnOneShotBMPFile               1036
#define btnOneShotJPEGFile              1037
#define grbOneShot                      1038
#define rgdFrameGrabberFormat1          1039
#define rgdFrameGrabberFormat2          1040
#define rgdFrameGrabberFormat3          1041
#define rgdFrameGrabberFormat4          1042
#define rgdFrameGrabberFormat5          1043
#define rgdFrameGrabberFormat6          1044
#define rgdFrameGrabberFormat           1045
#define rgdFrameGrabber1                1046
#define rgdFrameGrabber2                1047
#define rgdFrameGrabber3                1048
#define rgdFrameGrabber4                1049
#define rgdFrameGrabber                 1050
#define mmoTextOverlayString            1051
#define btnOneShotClipboard             1051
#define chkTextOverlayEnabled           1052
#define btnBurstModeClipboard           1052
#define rdgTextOverlayAlign1            1053
#define rdgTextOverlayAlign2            1054
#define rdgTextOverlayAlign3            1055
#define rdgTextOverlayAlign             1056
#define edtTextOverlayLeft              1057
#define edtTextOverlayTop               1058
#define edtTextOverlayWidth             1059
#define chkTextOverlayTransparent       1060
#define grbTextOverlay                  1061
#define chkFreeHandEnabled              1062
#define btnFreeHandErase                1063
#define grbFreeHand                     1064
#define chkLinesOverlayEnabled          1065
#define grbLinesOverlay                 1066
#define chkBitmapOverlayEnabled         1067
#define chkBitmapOverlayTransparent     1068
#define edtBitmapOvlerlayLeft           1069
#define edtBitmapOvlerlayTop            1070
#define btnBitmapOverlayResetSize       1071
#define edtBitmapOverlaySize            1072
#define tbrBitmapOverlaySize            1073
#define imgBitmapOverlay                1074
#define grbBitmapOverlay                1075
#define lblFrameOverlayRequiresFrameGrabber 1076
#define imgMotionDetected               1077
#define chkMotionDetectionEnabled       1078
#define chkReduceVideoNoise             1079
#define btnShowGridDialog               1080
#define chkCompareRed                   1081
#define chk_GreyScale                   1082
#define chkCompareBlue                  1083
#define chkCompareGreen                 1084
#define edtGrid                         1085
#define lblGridValid                    1086
#define grbGridString                   1087
#define edtGridColCount                 1088
#define edtGridRowCount                 1089
#define btnApplyGridSize                1090
#define edtXCell                        1091
#define edtYCell                        1092
#define btnSetCellsSensitivity          1093
#define edtCellSensitivity              1094
#define edtMaxMotionXY                  1095
#define edtMaxMotionCoord               1096
#define grbXYMaxMotion                  1097
#define edtMotionRatio                  1098
#define grbMotionRatio                  1099
#define mmoSensitivityGrid              1100
#define mmoMotionGrid                   1101
#define lblMotionDetectorRequiresFrameGrabber 1102
#define btnResetAll                     1103
#define rdgVideoRotation8               1104
#define rdgVideoRotation7               1105
#define rdgVideoRotation6               1106
#define rdgVideoRotation5               1107
#define rdgVideoRotation1               1108
#define rdgVideoRotation3               1109
#define rdgVideoRotation2               1110
#define rdgVideoRotation4               1111
#define rdgVideoRotation                1112
#define rdgDeinterlacing3               1113
#define rdgDeinterlacing2               1114
#define rdgDeinterlacing1               1115
#define rdgDeinterlacing                1116
#define chkFlipVertical                 1117
#define chkFlipHorizontal               1118
#define chkGreyScale                    1119
#define chkInvertColors                 1120
#define tbrBrightness                   1121
#define tbrContrast                     1122
#define tbrSaturation                   1123
#define tbrHue                          1124
#define grbSoftwareVideoProcessing      1125
#define chkCroppingEnabled              1126
#define chkCroppingOutbounds            1127
#define edtCroppingWidth                1128
#define edtCroppingHeight               1129
#define btnCroppingZoomReset            1130
#define trkCroppingX                    1131
#define trkCroppingY                    1132
#define trkCroppingZoom                 1133
#define grbCropping                     1134
#define vmr9FixRange                    1135
#define tbrVMR9Brightness               1136
#define tbrVMR9Contrast                 1137
#define tbrVMR9Saturation               1138
#define tbrVMR9Hue                      1139
#define grbVMR9Adjust                   1140
#define btnStopReencoding               1141
#define btnStartReencoding              1142
#define rdgReencodingMethod1            1143
#define rdgReencodingMethod2            1144
#define rdgReencodingMethod             1145
#define chkWMVOutput                    1146
#define chkUseFrameGrabber              1147
#define chkIncludeAudioStream           1148
#define chkUseCurrentVideoCompressor    1149
#define chkIncludeVideoStream           1150
#define chkUseCurrentAudioCompressor    1151
#define grbReencodingSettings           1152
#define edtDuration                     1153
#define edtStartTime                    1154
#define edtStopTime                     1155
#define btnDuration                     1156
#define grbStartStopTime                1157
#define edtDestinationVideoClip         1158
#define edtSourceVideoClip              1159
#define btnSourceVideoClip              1160
#define mmoChannelLog                   1161
#define edtTVChannel                    1162
#define btnSelect                       1163
#define edtChannelFrequency             1164
#define Command22                       1165
#define Command23                       1166
#define chkEnableFrequencyOverrides     1167
#define grbFrequencyOverride            1168
#define btnStartScan                    1169
#define btnStopScan                     1170
#define grbTVScan                       1171
#define grbTVChannel                    1172
#define rdgTunerInputType1              1173
#define rdgTunerInputType2              1174
#define rdgTunerInputType               1175
#define edtCountryCode                  1176
#define btnSetCountryCode               1177
#define grbCountryCode                  1178
#define btnResetAllOverrides            1179
#define grbTunerCountryCode             1180
#define cboVideoSource                  1181
#define btnStartPreview                 1182
#define btnStopPreview                  1183
#define grbPreview                      1184
#define btnFrameRate                    1185
#define edtFrameRate                    1186
#define grbFrameRate                    1187
#define cboVideoDevices                 1188
#define cboVideoInputs                  1189
#define cboVideoSizes                   1190
#define cboVideoSubtypes                1191
#define cboAnalogVideoStandard          1192
#define chkReduceDVFrameRate            1193
#define grbVsVideoCaptureDevice         1194
#define btnSelectFileOrUrl              1195
#define edtVideoSourceFileOrUrl         1196
#define grbVsFileOrUrl                  1197
#define chkScreenRecordingWithCursor    1198
#define grbVsScreenRecording            1199
#define rdgPreferredVideoSize1          1200
#define rdgPreferredVideoSize2          1201
#define rdgPreferredVideoSize3          1202
#define rdgPreferredVideoSize4          1203
#define rdgPreferredVideoSize5          1204
#define rdgPreferredVideoSize6          1205
#define rdgPreferredVideoSize7          1206
#define rdgPreferredVideoSize8          1207
#define rdgPreferredVideoSize9          1208
#define rdgPreferredVideoSize10         1209
#define rdgPreferredVideoSize11         1210
#define chkStretchPreferredVideoSize    1211
#define rdgPreferredVideoSize12         1212
#define rdgPreferredVideoSize13         1213
#define grbPreferredVideoSizes          1214
#define btnDeviceDialog                 1215
#define btnStreamDialog                 1216
#define btnCameraControlDialog          1217
#define btnVideoQualityDialog           1218
#define btnVideoControlDialog           1219
#define grbVideoDevicesDialogs          1220
#define btnAutoRefreshPreview           1221
#define chkRenderAudioDevice            1222
#define chkMuteAudioRendering           1223
#define tbrAudioVolume                  1224
#define tbrAudioBalance                 1225
#define grbAudioRendering               1226
#define cboAudioDevices                 1227
#define cboAudioInputs                  1228
#define chkAudioInputMono               1229
#define tbrAudioInputLevel              1230
#define tbrAudioInputBalance            1231
#define grbAudioCaptureDevice           1232
#define btnStartRecordingImmediately    1233
#define btnStartRecordingControlled     1234
#define btnStopRecording                1235
#define btnRenewRecordingFile           1236
#define chkRecordingCanPause            1237
#define btnPauseRecording               1238
#define btnResumeRecording              1239
#define grbAVIPauseResume               1240
#define rdgCompressMode1                1241
#define rdgCompressMode3                1242
#define rdgCompressMode2                1243
#define rdgCompressMode                 1244
#define rdgCompressType2                1245
#define rdgCompressType3                1246
#define rdgCompressType1                1247
#define rdgCompressType                 1248
#define cboVideoCompressors             1249
#define btnVideoCompressorSettings      1250
#define cboAudioCompressors             1251
#define btnAudioCompressorSettings      1252
#define rdgRecordingMethod1             1253
#define rdgRecordingMethod2             1254
#define rdgRecordingMethod              1255
#define chkAudioRecording               1256
#define cboAudioFormats                 1257
#define chkPreserveNativeFormat         1258
#define chkAVISaveToThisFile            1259
#define edtRecordingFileName            1260
#define chkOpenDML                      1261
#define chkPreallocFile                 1262
#define edtPreallocSize                 1263
#define btnCreatePreallocFileNow        1264
#define rdgNetworkStreaming1            1265
#define chkRecordingPauseCreatesNewFile 1265
#define rdgNetworkStreaming2            1266
#define rdgNetworkStreaming3            1267
#define btnViewDirectNetworkStreaming   1268
#define rdgNetworkStreaming             1269
#define edtNetworkPort                  1270
#define edtNetworkMaxUsers              1271
#define grbDirectASFStreaming           1272
#define edtPublishingPoint              1273
#define grbASFStreamingToWMServer       1274
#define chkASFFixedFrameRate            1275
#define cmbASFDeinterlaceMode           1276
#define edtASFVideoWidth                1277
#define edtASFVideoBitRate              1278
#define edtASFVideoQuality              1279
#define edtASFVideoMaxKeyFrameSpacing   1280
#define edtASFAudioChannels             1281
#define edtASFVideoHeight               1282
#define grbASFSettings                  1283
#define lsbProfiles                     1284
#define btnShowProfilesList             1285
#define edtProfileIndex                 1286
#define grbASFProfiles                  1287
#define btnFastFwd                      1288
#define btnFastRew                      1289
#define btnPlay                         1290
#define btnStop                         1291
#define btnPause                        1292
#define btnPlayBackwards                1293
#define btnPlayerOpenFile               1294
#define btnOpenLastClipRecorded         1295
#define btnOpenLastClipPlayed           1296
#define btnPlayerCloseFile              1297
#define btnPlayerOpenStreamingURL       1298
#define edtPlayerStreamingURL           1299
#define edtPlayerSpeedRatio             1300
#define edtPlayerFastSeekSpeed          1301
#define btnAutoPlay                     1302
#define chkPlayerAudioRendering         1303
#define chkRefreshPausedDisplay         1304
#define rdgDVPlaybackSize1              1305
#define rdgDVPlaybackSize2              1306
#define rdgDVPlaybackSize3              1307
#define rdgDVPlaybackSize4              1308
#define rdgDVPlaybackSize               1309
#define chk2ndVideoWindowActive         1310
#define btnEG2ndNewLocation2            1311
#define btnEG2ndNewLocation             1312
#define rdg2ndDisplayedOn2              1313
#define rdg2ndDisplayedOn1              1314
#define rdg2ndDisplayedOn               1315
#define chk2ndAutoSize                  1316
#define chk2ndStayOnTop                 1317
#define chk2ndMouseMovesWindow          1318
#define chk2ndFullScreen                1319
#define chk2ndKeepAspectRatio           1320
#define chk2ndUseVideoPort              1321
#define chk2ndEmbedded                  1322
#define grb2ndVideoWindow               1323
#define chk1stEmbedded                  1324
#define chk1stUseVideoPort              1325
#define chk1stKeepAspectRatio           1326
#define chk1stFullScreen                1327
#define chk1stMouseMovesWindow          1328
#define chk1stStayOnTop                 1329
#define chk1stAutoSize                  1330
#define rdg1stDisplayedOn1              1331
#define rdg1stDisplayedOn2              1332
#define rdg1stDisplayedOn               1333
#define btnEG1stNewLocation             1334
#define btnEG1stNewLocation2            1335
#define grbMainVideoWindow              1336
#define chk1stVideoWindowActive         1337
#define chkSetLogo                      1338
#define chkBorder                       1339
#define chkChangeCursor                 1340
#define rdgVideoRenderer5               1341
#define rdgVideoRenderer4               1342
#define rdgVideoRenderer1               1343
#define rdgVideoRenderer3               1344
#define rdgVideoRenderer2               1345
#define rdgVideoRenderer                1346
#define rdgVideoRenderer7               1347
#define rdgVideoRenderer6               1348
#define imgLogo                         1352
#define SnapImage                       1353
#define IDC_VIDEOGRABBER                1354
#define btnCreateCustomFont             1355
#define updGlobalGridSensitivity        1356
#define updGridColCount                 1357
#define updGridRowCount                 1358
#define updXCell                        1359
#define updYCell                        1360
#define updCellSensitivity              1361
#define updPlayerSpeedRatio             1362
#define updPlayerFastSeekSpeed          1363
#define btnMoreInfo                     1364
#define rdgRecordingMethod3             1365
#define chkBitmapOverlayUseTransparentColor 1367
#define chkBitmapOverlayAlphaBlending   1368
#define edtAlphaBlendingValue           1369
#define cmbBitmapOverlayTransparentColor 1373
#define IDC_VIDEOGRABBERVC61            1374
#define mnuDVplay                       32772
#define mnuDVstop                       32773
#define mnuDVfreeze                     32774
#define mnuDVthaw                       32775
#define mnuDVff                         32776
#define mnuDVrew                        32777
#define mnuDVrecord                     32778
#define mnuDVrecordFreeze               32779
#define mnuRecordStrobe                 32780
#define mnuDVstepFwd                    32781
#define mnuDVstepRev                    32782
#define mnuDVmodeShuttle                32783
#define mnuDVplayFastestFwd             32784
#define mnuDVplaySlowestFwd             32785
#define mnuDVplayFastestRev             32786
#define mnuDVplaySlowestRev             32787
#define mnuAbout                        32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1375
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
